CREATE TABLE called_urls
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id bigint REFERENCES sites(id) ON DELETE CASCADE,
    url VARCHAR NOT NULL,
    code VARCHAR NOT NULL,
    redirect_count bigint NOT NULL
);