package ru.job4j.urlshortcut.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.job4j.urlshortcut.dto.authentication.request.AuthRequestDto;
import ru.job4j.urlshortcut.dto.authentication.request.RegisterRequestDto;
import ru.job4j.urlshortcut.dto.authentication.response.AuthResponseDto;
import ru.job4j.urlshortcut.dto.authentication.response.RegisterResponseDto;
import ru.job4j.urlshortcut.security.jwt.JwtUtils;
import ru.job4j.urlshortcut.security.sitedetails.SiteDetailsImpl;
import ru.job4j.urlshortcut.service.site.SiteAuthService;

import javax.validation.Valid;

@Tag(name = "AuthController", description = "AuthController management APIs")
@Validated
@AllArgsConstructor
@RestController
@RequestMapping("/urlshortcut/auth")
public class AuthController {
    @Autowired
    private SiteAuthService siteAuthService;
    @Autowired
    private AuthenticationManager authenticationManager;
    @Autowired
    private JwtUtils jwtUtils;

    @Operation(
            summary = "Save a new site",
            description = "Save a new site as a user of this api. The id is autogenerated by the db. The response is a dto with a new login and password",
            tags = { "site", "post" })
    @ApiResponses({
            @ApiResponse(responseCode = "200", content = { @Content(schema = @Schema(implementation = RegisterResponseDto.class), mediaType = "application/json") }),
            @ApiResponse(responseCode = "400", content = { @Content(schema = @Schema()) }) })
    @PostMapping("/register")
    public ResponseEntity<RegisterResponseDto> registerSite(
            @Valid @RequestBody RegisterRequestDto registerRequestDto) {
        RegisterResponseDto registerDTO = siteAuthService.register(registerRequestDto);
        return ResponseEntity.ok(registerDTO);
    }

    @Operation(
            summary = "Authenticate a site",
            description = "Authenticates a site",
            tags = { "site", "post" })
    @ApiResponses({
            @ApiResponse(responseCode = "200", content = { @Content(schema = @Schema(implementation = AuthResponseDto.class), mediaType = "application/json") }),
            @ApiResponse(responseCode = "400", content = { @Content(schema = @Schema()) }) })
    @PostMapping("/signin")
    public ResponseEntity<AuthResponseDto> authenticateUser(
            @Valid @RequestBody AuthRequestDto authRequestDto) {
        Authentication authentication = authenticationManager
                .authenticate(new UsernamePasswordAuthenticationToken(authRequestDto.getLogin(), authRequestDto.getPassword()));
        SecurityContextHolder.getContext().setAuthentication(authentication);
        String jwt = jwtUtils.generateJwtToken(authentication);
        SiteDetailsImpl siteDetails = (SiteDetailsImpl) authentication.getPrincipal();
        return ResponseEntity
                .ok(new AuthResponseDto(jwt, siteDetails.getId(), siteDetails.getUsername()));
    }
}
